version: "3"
services:
  server:
    container_name: server
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - frontend
  client:
    container_name: client
    build: ./client
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - server
networks:
  frontend:
    driver: bridge
