# Deployment for the Node containers/pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
        - name: node-pod
          image: aminerachyd/ava-server
          ports:
            - containerPort: 5000
---
# Service for the Node containers/pods
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-depl
  ports:
    - port: 5000
      targetPort: 5000
