# Deployment for the React containers/pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-depl
spec:
  replicas: 2
  selector:
# Has to match the container label
    matchLabels:
      app: react-pod
  template:
    metadata:
      labels:
        app: react-pod
    spec:
      containers:
        - name: react-pod
          image: aminerachyd/ava-client
          ports:
            - containerPort: 80
---
# Service for the React containers/pods
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-service
  name: react-service
spec:
# Has to match the container label
  selector:
    app: react-pod
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
